nhsengland/datascience

docs/our_work/Publications.md
docs/our_work/c245_synpath.md
docs/our_work/c250_nhscorpus.md
docs/our_work/c338_poud.md
docs/our_work/c339_sas.md
docs/our_work/c399_privfinger.md
docs/our_work/ds218_rap_community_of_practice.md
docs/our_work/p11_synpathdiabetes.md
docs/our_work/p12_synthvae.md
docs/our_work/p14_mcr.md
docs/our_work/p21_synthvae.md
docs/our_work/p22_txtrayalign.md
docs/our_work/p23_stm.md
docs/our_work/p24_lime.md
docs/our_work/p31_txtrayalign2.md
docs/our_work/p32_phmdiabetes.md
docs/our_work/p33_patientsafetylms.md
docs/our_work/p34_hypergraphs.md
docs/our_work/p42_hypergraphs2.md
docs/our_work/p43_medcat.md
mkdocs.yml
requirements.txt

❓**What**: Fixing pages that don't have working titles due to mk docs variables and setting up the initial framework for other types of variables
🧠**Why?**:
👨‍💻**How?**:

Fix variable headings in md docs

---

docs/playbooks.md

❓**What**: This closes #11 . Added a table of existing playbooks to the page 
🧠**Why?**: to raise awareness of the playbooks, and the fact that we made them
👨‍💻**How?**: added to the playbooks page.

Made basic playbooks page

---

CODE_OF_CONDUCT.md
README.md
mkdocs.yml
overrides/home.html
overrides/partials/footer.html

❓**What**:
🧠**Why?**:
👨‍💻**How?**:

remove references to NHS or NHS digital + replace with NHS England

---

docs/stylesheets/extra.css
mkdocs.yml

❓**What**: Some small fixes to make the nav bar no-long bold, to order it, and to "flatten" them so that we don't see the same page name repeated twice at the top.
🧠**Why?**: Improves the look of the site.
👨‍💻**How?**: Some small changes to the CSS and mkdocs.yml

Fixed font, ordering and flattening of nav bar

---

docs/useful_links.md

Added Useful Links
❓**What**:
Useful links added mostly copying from the RAP useful links but with a change in focus not only RAP but also wider data science topics. 
🧠**Why?**:
Currently the page is blank. 
👨‍💻**How?**:
Changed the useful links markdown file to add these.

AH Add Useful Links

---

docs/what_is_data_science/Benefits of Data Science in the NHS.md
docs/what_is_data_science/How you can learn Data Science.md
docs/what_is_data_science/index.md
overrides/home.html

❓**What**: Filled in the empty pages under "what is data science". This closes issue
🧠**Why?**: We need to fill in each part of the website with some initial content.
👨‍💻**How?**:

Sh what is data science

---

mkdocs.yml
overrides/home.html

❓**What**: 
1. temporarily removes tools section 
2. makes homepage fit better on smaller screens. 
🧠**Why?**:
1. currently this page is empty and it has been agreed that for the MVP it is not necessary for now
2. carousel wasnt visible before
👨‍💻**How?**:

Remove tools page

---

docs/about.md

❓**What**: Add people and our work to the about the team page
🧠**Why?**: part of the MVP. 
👨‍💻**How?**: Adding some markdown

AIB Refine our team page

---

mkdocs.yml

❓**What**: hide the [template page](https://nhsengland.github.io/datascience/our_work/template-project/)
🧠**Why?**: it doesn't need to be in the project list, and looks sloppy.
👨‍💻**How?**: changed the mkdocs.yml to use a regex to filter it out.

Hides the template "our work" page

---

docs/about.md

❓**What**: add more github usernames
🧠**Why?**: found some people's users that I hadnt found before
👨‍💻**How?**: adding them to the about the team page 

add more github usernames

---

docs/our_work/index.md

❓**What**: improve layout of our work
🧠**Why?**: looked too blocky from feedback from others
👨‍💻**How?**: added some titles, centered the image and formatted

improve our work

---

docs/our_work/ai-deep-dive.md
docs/our_work/long-stay.md
docs/our_work/project-flow.md
docs/our_work/renal-health-prediction.md
docs/our_work/template-project.md
mkdocs.yml
overrides/main.html
overrides/partials/header.html

❓**What**: initial version of functioning tags for projects + adding a search bar
🧠**Why?**: makes navigation through projects and the website easier 
👨‍💻**How?**: adding tags plugin + changing settings for search plug in

add tags + search bar

---

overrides/partials/header.html

❓**What**: added usermaven website tracking
🧠**Why?**: see what pages are most used and the effect of promotion
👨‍💻**How?**: added tracking into header as provided by guidance from @jenniferstruthers1-nhs and the usermaven website

website tracking

---

mkdocs.yml

❓**What**: removed all of the unnecessary lines from yml file
🧠**Why?**: there was a lot of holdover packages + other sections in the file that were left from copying the RAP website template
👨‍💻**How?**: went through + individually removed the ones I wasnt sure about to check whether anything changed on the website from removing them, and readded those that were necessary. 

remove unneeded sections mkdocs.yml

---

overrides/home.html
overrides/partials/footer.html

❓**What**: made edits to the footer + one of the home page buttons
🧠**Why?**: weren't accurate + also might not be approved by central comms
👨‍💻**How?**: changing the text 

improve front page content

---

docs/about.md
docs/javascripts/tablefilter.js
docs/javascripts/tablesort.js
docs/stylesheets/extra.css
mkdocs.yml

❓**What**: refactoring members table somewhat 
🧠**Why?**: hard to see, not very navigable
👨‍💻**How?**: made it into a html and added searching by column 

AIB review of our members table

---

docs/meta_page.md
mkdocs.yml

❓**What**: more content in the meta page
🧠**Why?**: was pretty empty and therefore not useful
👨‍💻**How?**: added acknowlegements as well as a contributing page 

simple improvements to meta page

---

docs/our_work/ct-alignment.md
docs/our_work/template-project.md
mkdocs.yml
requirements.txt

❓**What**: removing tags from tags list + fixing one heading
🧠**Why?**: template tags being present on tags list looks bad
👨‍💻**How?**: commented out the tags in the template (the alternative neater method is behind a paywall at mkdocs :( )

AIB remove sample tags from list

---

docs/our_work/Publications.md

❓**What**: fixed some formatting with publications page
🧠**Why?**:  looked bad
👨‍💻**How?**: added the thing at the bottom that makes the header not render twice, and reordered the publications for them to be in numerical order

fixed some issues with the publications page

---

docs/what_is_data_science/How you can learn Data Science.md

❓**What**: Added a link to the PD newsletter site (now open to all) to the "How you can learn data science" section. Open to changes. In the near future I think the PD team might also be interested in adding some info to the resources they offer and I think this would be a good place for it. 
🧠**Why?**: To advertise some of the resources our team have to learn more about DS.
👨‍💻**How?**: By adding some text and a button to the page.

JS add PD newsletter link

---

docs/our_work/Publications.md

❓**What**: Update Publications with ZH paper and reorder
🧠**Why?**: Showcase publication and reorder so latest paper appears at the top of the page
👨‍💻**How?**: Bit of markdown
- MacOS Sonoma 14.3

Update Publications with ZH paper

---

mkdocs.yml

❓**What**: reducing project grouping, and reorganising some of the grouping
🧠**Why?**: current structure is too complicated, and a bug made the navigation skip around
👨‍💻**How?**:

Reduce groupings and rearrange projects

---

docs/PhDInterns.md
mkdocs.yml

❓**What**: Relating to Issue #23 - Add PhD Internship content
🧠**Why?**: To connect this site to the intern microsite
👨‍💻**How?**: Addition of new tab between Data Science in NHS England and Articles
- MacOS Sonoma 14.3

Addition of PhDIntern Page

---

overrides/home.html
utils/list-projects.py

❓**What**: randomise which projects get selected to be on the carousel 
🧠**Why?**: means all the projects get showcased
👨‍💻**How?**: javascript that out of a list of projects selects a random 9, then goes into their HTML and finds their title and first image to use 

Randomise Carousel Projects

---

docs/our_work/ratings-and-reviews.md

❓**What**: Updating link to automod flask app repo
🧠**Why?**: New public repo now the code is published
👨‍💻**How?**: Updated link and removed 'coming soon' reminder

MT updating automod repo link to the public version

---

mkdocs.yml

❓**What**: change table of contents formatting
previous toc:
new toc: 
🧠**Why?**: suggestion from @jenniferstruthers1-nhs and looks nicer
👨‍💻**How?**: added setting in mkdocs yml 

integrated toc

---

mkdocs.yml
requirements.txt

❓**What**: make external links open in new tab
🧠**Why?**: want to keep people on the website rather than direct them off
👨‍💻**How?**: plug in made for it

open links in new tab

---

docs/our_work/ds251_RAG.md
mkdocs.yml

❓**What**: placeholder for RAG page
🧠**Why?**: Ben needed a QR for the haca poster and needs a placeholder page to fill after the HACA deadline
👨‍💻**How?**: create new project page

"Adds skeleton page for RAG"

---

docs/stylesheets/extra.css
overrides/home.html
utils/list-projects.py

❓**What**: remove carousel and add tiles
🧠**Why?**: bad for accessibility
👨‍💻**How?**:

Aib better landing page

---

docs/about.md
mkdocs.yml
overrides/home.html

❓**What**:  Removal of "What is Data Science" as this is not our remit and incomplete which gives a poor initialk impression of a asoirational but unfinished team.   Updated Data Science in NHSE to focus on the three teams.  Included some "how do I learn data science" content in there.  Moves the Articles page to the right as currently underpopulated to be one of the first things users come to.   
🧠**Why?**:  Issue 72 and 104
👨‍💻**How?**:  Content update and changes to .yml
- Mac OS Sonoma 14.3

Major remove what is update ds in nhse

---

docs/about.md

❓**What**: about.md
🧠**Why?**: getting an github bots permission error 403 in https://github.com/nhsengland/nhs-r-reporting/pull/49
👨‍💻**How?**: make the a PR with a tiny change to website content and attempt to merge
- Tested on a corporate laptop - Dell Latitude 5430 i7, 16GB RAM, 256GB hard drive
- Operating System: Windows 10 Enterprise
- Python version: Python 3.10.7
- IDE: Visual Studio Code 1.89.0

CK Test a 403 error reproducibility

---

docs/our_work/ratings-and-reviews.md

❓**What**: Adding link and updating wording
🧠**Why?**: We have a new public repo for our ML model work
👨‍💻**How?**: added link

Adding a link to new automod models public repo

---

CONTRIBUTE.md
README.md
docs/our_work/ai-ethics.md
docs/our_work/p14_mcr.md
mkdocs.yml

❓**What**: Adds a project page for the AI Ethics project

HS Create Ethical AI page

---

docs/our_work/Publications.md

add INSTANT publication on AI Assurance

add publication

---

mkdocs.yml

❓**What**: changed phd internships page nav bar title
🧠**Why?**: it was a temporary title that was just the name of the file and looked bad
👨‍💻**How?**:

temp title removed for phd internships page

---

docs/our_work/Publications.md

❓**What**: broken links in publications fixed
🧠**Why?**:
👨‍💻**How?**:

fix links in publications

---

.all-contributorsrc
docs/codebases.md
docs/meta_page.md

❓**What**:
🧠**Why?**:
👨‍💻**How?**:

add contributors bot

---

.all-contributorsrc
README.md
docs/meta_page.md

❓**What**:
🧠**Why?**:
👨‍💻**How?**:

Aib all contributors

---

overrides/home.html

❓**What**: fixes #158 
🧠**Why?**: https://github.com/nhsengland/datascience/issues/158
👨‍💻**How?**: removed outline

removed outline from .tile:hover in home.html

---

docs/meta_page.md

❓**What**:
🧠**Why?**:
👨‍💻**How?**:

remove duplication in contributions page

---

docs/our_work/tags.md

❓**What**: fix tag links in tag navigator
🧠**Why?**: mkdocs appear to have updated how tag links work, and it meant that our tag navigation no longer worked
👨‍💻**How?**: add tag: to the start of all the tag links

fix broken tag links

---

docs/articles/posts/20250314_gen_ai_search_engagement.md

❓**What**: fix blog post
🧠**Why?**: bullet points where not rendering correctly
👨‍💻**How?**: adding a space between the paragraoh and the bullet points

fix bullet points

---

docs/articles/.authors.yml
docs/articles/posts/Presentation.md

❓**What**:
🧠**Why?**:
👨‍💻**How?**:

Presentationblog

---

CONTRIBUTE.md
docs/our_work/template-project.md

❓**What**: improving documentation on contributing to the DS website
🧠**Why?**: currently it requires me to go through it with new people contributing. 
👨‍💻**How?**:

Aib improve contributing guidance

---

docs/our_work/ratings-and-reviews.md

❓**What**: Adding a new link to the outputs section for the ATRS record
🧠**Why?**: The ATRS gives much more detail on how the automoderation tool works and shows our commitment to transparency
👨‍💻**How?**: Added a link to outputs section
- Only minor change so hosted locally and checked visually

MT ATRS link for the ratings and reviews page

---

mkdocs.yml

❓**What**: when searching the website it already has a logo, which is the favicon image.
But this is different from the image that appears when you search Google: 
Chat GPT told me that Google uses Open Graph (OG) tags for preview images, and that this was how to implement it. 
Thing is, we won't know if it worked/looks okay until it's merged, and Google has picked up the change. 
I was also told once it's merged we can request a reindexing to speed up the process: https://support.google.com/webmasters/answer/9012289?hl=en#request_indexing
🧠**Why?**: So it looks better
👨‍💻**How?**: Adding to the yaml

Get NHS Logo as OpenGraph image (in the google search)

---

docs/about.md

❓**What**: Updated team list. I don't think we have an official one anywhere? So it was kind of top of my head. I'm very unfamiliar with SDE structure so that's almost definitely wrong
🧠**Why?**: It's quite out of date.
👨‍💻**How?**:

updated team list

---

docs/about.md

❓**What**: fix button linking to PD newsletter
🧠**Why?**: it had broken and wasnt rendeirng correctly
👨‍💻**How?**: coding it as HTML instead of a mnix of HTML and markdown syntax

fix PD newsletter button

---

README.md
docs/about.md
docs/playbooks.md
docs/useful_links.md
docs/what_is_data_science/How you can learn Data Science.md
overrides/partials/footer.html

❓**What**: replace data science team mentions with either the profession or the new team name
🧠**Why?**: team is rebranding
👨‍💻**How?**: find and replace

remove data science team mentions
